version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rsoi
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345sql
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345sql
      - MYSQL_DATABASE=rsoi
#      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345sql
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}
